### ISSUE TITLE
Images for ReadMe

### ISSUE THREAD

**Issue by Kymbolde** [GraphicApp/Graphic#24]
![](https://files.slack.com/files-pri/T039C2PUY-F4095HLG3/cpu_data.png)

![](https://files.slack.com/files-pri/T039C2PUY-F3ZKTTNGG/memory.png)

![](https://files.slack.com/files-pri/T039C2PUY-F4123DXJT/monitorpage.png)

![](https://files.slack.com/files-pri/T039C2PUY-F40B7V69Y/settings_page.png)

**Comment by matthewsidneyjacobs** [comment]
These images don't work. Please make a PR not an issue. Also add the images as a relative path to the app's root, not slack links.
@Kymbolde
